// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {downloader} from '../models';
import {bootstrap} from '../models';
import {history} from '../models';
import {config} from '../models';

export function AnalyzePlaylistURL(arg1:string):Promise<downloader.VideoInfo>;

export function AnalyzeURL(arg1:string):Promise<downloader.VideoInfo>;

export function CancelAllDownloads():Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function CheckBootstrap():Promise<bootstrap.BootstrapStatus>;

export function ClearCompleted():Promise<void>;

export function ClearHistory():Promise<void>;

export function GetDiagnostics():Promise<string>;

export function GetHistory():Promise<Array<history.HistoryEntry>>;

export function GetQueue():Promise<Array<downloader.QueueItem>>;

export function GetSettings():Promise<config.Config>;

export function HideOverlay():Promise<void>;

export function HideWindow():Promise<void>;

export function InstallYtDlp():Promise<bootstrap.BootstrapStatus>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function RemoveDownload(arg1:string):Promise<void>;

export function RemoveHistoryEntry(arg1:string):Promise<void>;

export function RetryDownload(arg1:string):Promise<void>;

export function SaveSettings(arg1:config.Config):Promise<void>;

export function SelectFolder():Promise<string>;

export function ShowOverlay():Promise<void>;

export function ShowWindow():Promise<void>;

export function StartBatchDownload(arg1:Array<string>,arg2:string,arg3:string):Promise<Array<string>>;

export function StartDownload(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ToggleOverlay():Promise<void>;
