// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzePlaylistURL(arg1) {
  return window['go']['main']['App']['AnalyzePlaylistURL'](arg1);
}

export function AnalyzeURL(arg1) {
  return window['go']['main']['App']['AnalyzeURL'](arg1);
}

export function CancelAllDownloads() {
  return window['go']['main']['App']['CancelAllDownloads']();
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CheckBootstrap() {
  return window['go']['main']['App']['CheckBootstrap']();
}

export function ClearCompleted() {
  return window['go']['main']['App']['ClearCompleted']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetDiagnostics() {
  return window['go']['main']['App']['GetDiagnostics']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetQueue() {
  return window['go']['main']['App']['GetQueue']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HideOverlay() {
  return window['go']['main']['App']['HideOverlay']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function InstallYtDlp() {
  return window['go']['main']['App']['InstallYtDlp']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RemoveDownload(arg1) {
  return window['go']['main']['App']['RemoveDownload'](arg1);
}

export function RemoveHistoryEntry(arg1) {
  return window['go']['main']['App']['RemoveHistoryEntry'](arg1);
}

export function RetryDownload(arg1) {
  return window['go']['main']['App']['RetryDownload'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function ShowOverlay() {
  return window['go']['main']['App']['ShowOverlay']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartBatchDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartBatchDownload'](arg1, arg2, arg3);
}

export function StartDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3);
}

export function ToggleOverlay() {
  return window['go']['main']['App']['ToggleOverlay']();
}
